[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4" # Web framework for Rust
tokio = { version = "1", features = ["full"] } # Async runtime for Actix

